<?php

namespace Isssr\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository
{
	public function findByOwner($uid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.owner = '.$uid)
				->getResult();
	}
	
	public function findByEnactor($uid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.enactor = '.$uid)
				->getResult();
	}
 	
	public function queryTitle($title)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.title LIKE '."'%".$title."%'")
				->getResult();
	}
	
	public function queryDescription($description)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.description LIKE '."'%".$description."%'")
				->getResult();
	}
}
