<?php

namespace Isssr\CoreBundle\Repository;

use Isssr\CoreBundle\Entity\UserInGoal;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository
{
	public function findByOwner($uid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:UserInGoal g '.
				'WHERE g.user = '.$uid.' AND g.role = '.UserInGoal::ROLE_OWNER)
				->getResult();
	}
	
	public function findByEnactor($uid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:UserInGoal g '.
				'WHERE g.user = '.$uid.' AND g.role = '.UserInGoal::ROLE_ENACTOR)
				->getResult();
	}
 	
	public function queryTitle($title)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.title LIKE '."'%".$title."%'")
				->getResult();
	}
	
	public function queryDescription($description)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT g FROM IsssrCoreBundle:Goal g '.
				'WHERE g.description LIKE '."'%".$description."%'")
				->getResult();
	}
}
