<?php

namespace Isssr\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepositoy extends EntityRepository
{
	
	public function findByRoot($rid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT n FROM IsssrCoreBundle:Grid n '.
				'WHERE n.root = '.$rid)
				->getResult();
	}
	
}
