<?php

namespace Isssr\CoreBundle\Repository;

use Isssr\CoreBundle\Entity\Measurement;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementRepository extends EntityRepository
{
	public function findByOwner($uid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT m FROM IsssrCoreBundle:Measurement m '.
				'WHERE m.question = '.$qid)
				->getResult();
	}
	
	
}
