<?php

namespace Isssr\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
	
	public function findByGoal($gid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT n FROM IsssrCoreBundle:Node n '.
				'WHERE n.goal = '.$gid)
				->getResult();
	}
	
	public function findByStrategy($sid)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT n FROM IsssrCoreBundle:Node n '.
				'WHERE n.strategy = '.$sid)
				->getResult();
	}
}
