<?php

namespace Isssr\CoreBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	
	public function findByUsername($username)
	{
		$val = $this->findOneBy(array('username' => $username));
		return $val;
	}
	
	
}
