expression:
    pattern:  /goal/{id}/
    defaults: { _controller: "IsssrCoreBundle:Expression:index" }


expression_new:
    pattern:  /goal/{id}/new
    defaults: { _controller: "IsssrCoreBundle:Expression:new" }

expression_create:
    pattern:  /goal/{id}/create
    defaults: { _controller: "IsssrCoreBundle:Expression:create" }
    requirements: { _method: post }
