goal:
    pattern:  /
    defaults: { _controller: "IsssrCoreBundle:Goal:index" }

goal_as:
    pattern:  /as/{role}
    defaults: { _controller: "IsssrCoreBundle:Goal:indexAs" }

goal_show:
    pattern:  /{id}/show
    defaults: { _controller: "IsssrCoreBundle:Goal:show" }
    
goal_new:
    pattern:  /new
    defaults: { _controller: "IsssrCoreBundle:Goal:new" }

goal_create:
    pattern:  /create
    defaults: { _controller: "IsssrCoreBundle:Goal:create" }
    requirements: { _method: post }

goal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IsssrCoreBundle:Goal:edit" }

goal_notify_supers:
    pattern:  /{id}/notifysupers
    defaults: { _controller: "IsssrCoreBundle:Goal:notifySupers" }
    requirements: { _method: post }
    
goal_update:
    pattern:  /{id}/update
    defaults: { _controller: "IsssrCoreBundle:Goal:update" }
    requirements: { _method: post }

goal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IsssrCoreBundle:Goal:delete" }
    requirements: { _method: post }
    
goal_accept:
    pattern:  /{id}/accept
    defaults: { _controller: "IsssrCoreBundle:Goal:roleAccepts" }
    requirements: { _method: post }
    
goal_reject:
    pattern:  /{id}/reject
    defaults: { _controller: "IsssrCoreBundle:Goal:roleRejects" }
    requirements: { _method: post }
    
goal_send_to_enactor:
    pattern:  /{id}/sendtoenactor
    defaults: { _controller: "IsssrCoreBundle:Goal:sendToEnactor" }

