grid:
    pattern:  /
    defaults: { _controller: "IsssrCoreBundle:Grid:index" }

grid_show:
    pattern:  /{id}/show
    defaults: { _controller: "IsssrCoreBundle:Grid:show" }

grid_json:
    pattern:  /{id}/json
    defaults: { _controller: "IsssrCoreBundle:Grid:json" }