measureunit:
    pattern:  /
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:index" }

measureunit_show:
    pattern:  /{id}/show
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:show" }

question_measureunit_new:
    pattern:  /new/{qid}
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:new" }

question_measureunit_create:
    pattern:  /create/{qid}
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:create" }
    requirements: { _method: post }

question_measureunit_select:
    pattern:  /select/{qid}
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:select" }
    requirements: { _method: post }

measureunit_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:edit" }

measureunit_update:
    pattern:  /{id}/update
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:update" }
    requirements: { _method: post }

measureunit_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:delete" }
    requirements: { _method: post }

measureunit_close:
    pattern:  /{id}/close
    defaults: { _controller: "IsssrCoreBundle:MeasureUnit:close" }