user:
    pattern:  /
    defaults: { _controller: "IsssrCoreBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "IsssrCoreBundle:User:show" }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IsssrCoreBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "IsssrCoreBundle:User:update" }
    requirements: { _method: post }
