isssr_core_homepage:
    pattern:  /
    defaults: { _controller: "IsssrCoreBundle:Default:index" }

IsssrCoreBundle_goal:
        resource: "@IsssrCoreBundle/Resources/config/routing/goal.yml"
        prefix:   /goal
        
IsssrCoreBundle_user:
        resource: "@IsssrCoreBundle/Resources/config/routing/user.yml"
        prefix:   /user
 
IsssrCoreBundle_tag:
        resource: "@IsssrCoreBundle/Resources/config/routing/tag.yml"
        prefix:   /tag

IsssrCoreBundle_roles:
        resource: "@IsssrCoreBundle/Resources/config/routing/roles.yml"
        prefix:   /roles
        
IsssrCoreBundle_search:
        resource: "@IsssrCoreBundle/Resources/config/routing/search.yml"
        prefix:   /search
        
IsssrCoreBundle_rejectjust:
        resource: "@IsssrCoreBundle/Resources/config/routing/rejectjust.yml"
        prefix:   /rejectjust
        
IsssrCoreBundle_enactoringoal:
        resource: "@IsssrCoreBundle/Resources/config/routing/enactoringoal.yml"
        prefix:   /enactoringoal
        
IsssrCoreBundle_mmdmingoal:
        resource: "@IsssrCoreBundle/Resources/config/routing/mmdmingoal.yml"
        prefix:   /mmdmingoal
        