parameters:
    isssr_hm.class: Isssr\CoreBundle\Services\HierarchyManager
    isssr_gm.class: Isssr\CoreBundle\Services\GoalManager
    isssr_nm.class: Isssr\CoreBundle\Services\NotifierManager
    isssr_wm.class: Isssr\CoreBundle\Services\WorkflowManager
    isssr_im.class: Isssr\CoreBundle\Services\InterpretativeModel

services:

    isssr_core.hierarchymanager:
        class: "%isssr_hm.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        
    isssr_core.goalmanager:
        class: "%isssr_gm.class%"
        arguments: ["@doctrine.orm.entity_manager", "@isssr_core.interpretativemodel"]
        
    isssr_core.notifiermanager:
        class: "%isssr_nm.class%"
        arguments: ["@doctrine.orm.entity_manager", "@mailer"]
        
    isssr_core.workflowmanager:
        class: "%isssr_wm.class%"
        arguments: ["@doctrine.orm.entity_manager", "@isssr_core.goalmanager"]
        
    isssr_core.interpretativemodel:
        class: "%isssr_im.class%"
        arguments: ["@doctrine.orm.entity_manager"]