parameters:
#    isssr_core.example.class: Isssr\CoreBundle\Example

services:
#    isssr_core.example:
#        class: %isssr_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
