parameters:
    isssr_hm.class: Isssr\CoreBundle\Services\HierarchyManager
    isssr_gm.class: Isssr\CoreBundle\Services\GoalManager

services:

    isssr_core.hierarchymanager:
        class: "%isssr_hm.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        
    isssr_core.goalmanager:
        class: "%isssr_gm.class%"
        arguments: ["@doctrine.orm.entity_manager"]