parameters:
    twitter_plus_core.class: Isssr\CoreBundle\Services\HierarchyManager

services:

    isssr_core.hierarchymanager:
        class: "%twitter_plus_core.class%"
        arguments: ["@doctrine.orm.entity_manager"]